name: Build presentation

on:
  push:
    branches:
      - 'main'

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Publish presentation
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: presentation
          target-branch: gh_pages
